name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  TERRAFORM_VERSION: "1.13.5"

jobs:

  lint-and-validate:
    name: Lint and Validate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew
            ~/.cache/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/ci.yml') }}
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install and upgrade pre-commit, tflint, trivy
        run: |
          brew update
          brew install pre-commit tflint trivy
          brew upgrade pre-commit tflint trivy
      - name: Cache pre-commits
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Install pre-commit hooks
        run: pre-commit install
    # Trivy and TFLint are run via pre-commit hooks
      - name: Run pre-commit checks
        run: pre-commit run --show-diff-on-failure --color=always --all-files
